//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLMUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERILER()
        {
            this.TBLSATIS = new HashSet<TBLSATI>();
        }
    
        public int MUSTERIID { get; set; }

        [Required(ErrorMessage ="Bu alan boş bırakılamaz!")]
        [StringLength(50, ErrorMessage ="Girdiğiniz değer 50 karakterden uzun olamaz!")]
        public string MUSTERIAD { get; set; }

        [Required(ErrorMessage = "Bu alan boş bırakılamaz!")]
        [StringLength(50, ErrorMessage = "Girdiğiniz değer 50 karakterden uzun olamaz!")]
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATI> TBLSATIS { get; set; }
    }
}
